# Generated by Django 2.2.5 on 2020-09-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200912_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='guests',
            field=models.IntegerField(default=2, help_text='How many people will be staying?'),
            preserve_default=False,
        ),
    ]
