# Generated by Django 2.2.5 on 2020-09-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_room_guests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='guests',
        ),
    ]
