# Generated by Django 2.2.5 on 2020-10-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_auto_20200911_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='converstation',
            new_name='conversation',
        ),
    ]
