# Generated by Django 2.2.5 on 2020-10-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200911_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
    ]
