# Generated by Django 2.2.5 on 2020-10-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='guest',
        ),
    ]
